"use client";

// import type { Metadata } from "next";
import "./globals.css";
import { useState } from "react";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [count, setCount] = useState(0);
  return (
    <html lang="en">
      <body>
        {children}
        <button onClick={() => setCount((prev) => prev + 1)}></button>
        {count}
      </body>
    </html>
  );
}
